---
## General pipeline parameters:

# Name of the pipeline:
pipeline: "pipeline-transcriptome-de_paired"
# ABSOLUTE path to directory holding the working directory:
workdir_top: "Workspaces"
# Results directory:
resdir: "results"
# Repository URL:
repo: "https://github.com/nanoporetech/pipeline-transcriptome-de/tree/paired_dge_dtu"

## Pipeline-specific parameters:

transcriptome: "Homo_sapiens.GRCh38.cdna.all.fa"

annotation: "Homo_sapiens.GRCh38.93.gtf"

# The samples should be named as <sample_id>.<patient_id>:
control_samples:
    C1.p1: "C1.fq"
    C2.p2: "C2.fq"
    C3.p3: "C3.fq"

treated_samples:
    IR1.p1: "IR1.fq"
    IR2.p2: "IR2.fq"
    IR3.p3: "IR3.fq"

minimap_index_opts: ""

minimap2_opts: ""

maximum_secondary: 100

secondary_score_ratio: 1.0

salmon_libtype: "SF"

# Count filtering options - customize these according to your experimental design:

# Genes expressed in minimum this many samples:
min_samps_gene_expr: 3
# Transcripts expressed in minimum this many samples:
min_samps_feature_expr: 1
# Minimum gene counts:
min_gene_expr: 10
# Minimum transcript counts:
min_feature_expr: 3

threads: 50

