---
## General pipeline parameters:

# Name of the pipeline:
pipeline: "pipeline-transcriptome-de_bam_dte"
# ABSOLUTE path to directory holding the working directory:
workdir_top: "Workspaces"
# Results directory:
resdir: "results"
# Repository URL:
repo: "https://github.com/nanoporetech/pipeline-transcriptome-de/tree/bam_count_dte"

## Pipeline-specific parameters:

transcriptome: "Homo_sapiens.GRCh38.cdna.all.fa"

control_samples:
    C1: "C1.fq"
    C2: "C2.fq"
    C3: "C3.fq"

treated_samples:
    IR1: "IR1.fq"
    IR2: "IR2.fq"
    IR3: "IR3.fq"

minimap_index_opts: ""

minimap2_opts: ""

minimum_mapping_quality: 10

threads: 50
