---
## General pipeline parameters:

# Name of the pipeline:
pipeline: "pipeline-transcriptome-de_phe"
# ABSOLUTE path to directory holding the working directory:
workdir_top: "/nfs/groups_ech/apps/active/bsipos/Workspaces"
# Results directory:
resdir: "results"
# Repository URL:
repo: "git URL"

## Pipeline-specific parameters:

transcriptome: "/nfs/groups_ech/apps/active/bsipos/data/phe_cdna/ref/Homo_sapiens.GRCh38.cdna.all.fa"

control_samples:
    C1: "/nfs/groups_ech/apps/active/bsipos/data/phe_cdna/C1.fq"
    C2: "/nfs/groups_ech/apps/active/bsipos/data/phe_cdna/C2.fq"
    C3: "/nfs/groups_ech/apps/active/bsipos/data/phe_cdna/C3.fq"

treated_samples:
    IR1: "/nfs/groups_ech/apps/active/bsipos/data/phe_cdna/IR1.fq"
    IR2: "/nfs/groups_ech/apps/active/bsipos/data/phe_cdna/IR2.fq"
    IR3: "/nfs/groups_ech/apps/active/bsipos/data/phe_cdna/IR3.fq"

minimap_index_opts: ""

minimap2_opts: ""

minimum_mapping_quality: 10

# Abundance estimation parameters:

min_aln_fraction: 0.5

min_read_length: 0

nr_em_iters: 10

score_threshold: 0.95

threads: 50
